// import localFont from "next/font/local";
import "./Global.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>ASHEE</h1>
        <div style={{ border: "1px solid black" }}>{children}</div>
      </body>
    </html>
  );
}
